function scenario_sets = build_metric_scenarios_exact()
%BUILD_METRIC_SCENARIOS_EXACT Scenario families tuned for the exact model.
%
%   The exact weak-turbulence correlation model decays on the centimeter
%   scale and has smaller scintillation than the Gamma-Gamma approximation.
%   These scenarios use smaller receiver spacing and a lower photon budget
%   range so that the curves separate visibly.

    scenario_sets(1).key = 'Turbulence';
    scenario_sets(1).title = 'Turbulence strength';
    scenario_sets(1).legend_title = 'Cn2 scale';
    scenario_sets(1).scenarios = [ ...
        make_scenario('weak', 'Weak', ...
            {'turbulence_strength_scale', 'ring_radii', 'ring_num_receivers'}, ...
            {0.40, 0.05, 3}); ...
        make_scenario('medium', 'Medium', ...
            {'turbulence_strength_scale', 'ring_radii', 'ring_num_receivers'}, ...
            {1.00, 0.05, 3}); ...
        make_scenario('strong', 'Strong', ...
            {'turbulence_strength_scale', 'ring_radii', 'ring_num_receivers'}, ...
            {2.50, 0.05, 3})];

    scenario_sets(2).key = 'Correlation';
    scenario_sets(2).title = 'Receiver spacing correlation';
    scenario_sets(2).legend_title = 'Array spacing';
    scenario_sets(2).scenarios = [ ...
        make_scenario('compact', 'Compact, high corr', ...
            {'ring_radii', 'ring_num_receivers'}, {0.02, 3}); ...
        make_scenario('default', 'Default', ...
            {'ring_radii', 'ring_num_receivers'}, {0.05, 3}); ...
        make_scenario('spread', 'Spread, low corr', ...
            {'ring_radii', 'ring_num_receivers'}, {0.20, 3})];

    scenario_sets(3).key = 'ReceiverNumber';
    scenario_sets(3).title = 'Receiver number';
    scenario_sets(3).legend_title = 'Rings';
    scenario_sets(3).scenarios = [ ...
        make_scenario('M2', 'M=2', {'ring_radii', 'ring_num_receivers'}, {0.05, 2}); ...
        make_scenario('M3', 'M=3', {'ring_radii', 'ring_num_receivers'}, {0.05, 3}); ...
        make_scenario('M6', 'M=6', {'ring_radii', 'ring_num_receivers'}, {0.05, 6})];
end

function scenario = make_scenario(key, label, fields, values)
    scenario.key = key;
    scenario.label = label;
    scenario.fields = fields;
    scenario.values = values;
end
